#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

echo "Disabling Buildkit"
KUBECTL_ENV="${SNAP_DATA}/args/kubectl-env"
run_with_sudo sed -i '/^# buildkit start/,/^# buildkit end/{/#buildkit end/!d}' "${KUBECTL_ENV}"

run_with_sudo rm -rf "${SNAP_DATA}/bin/kubectl-buildkit"
run_with_sudo rm -rf "${SNAP_DATA}/bin/kubectl-build"
run_with_sudo rm -rf "$SNAP_USER_COMMON/buildkit.lock"

