#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"


echo "Disabling postgresql"

$HELM uninstall postgresql -n cnpg-system | true

$KUBECTL delete pvc -l release=postgresql
