#!/usr/bin/env bash

set -eu

source "$SNAP/actions/common/utils.sh"

ENABLE="$SNAP/microk8s-enable.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

$ENABLE dns
$ENABLE helm3
$ENABLE hostpath-storage

$HELM repo add cnpg https://cloudnative-pg.github.io/charts
$HELM repo update
$HELM upgrade --install cnpg --namespace cnpg-system --create-namespace cnpg/cloudnative-pg

echo "The CloudNativePG Postgresql Operator is installed"

