#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

echo "Enabling KubeVela"

if [ ! -f "${SNAP_DATA}/bin/kubectl-vela" ]
then
  VELA_VERSION="v1.6.0-alpha.4"

  if ! [ $SNAP_ARCH == "arm64" ] && ! [ $SNAP_ARCH == "amd64" ]; then
    echo "Architecture $SNAP_ARCH not supported"
    exit 1
  fi


  echo "Fetching KubeVela CLI version $VELA_VERSION for $SNAP_ARCH."
  run_with_sudo mkdir -p "${SNAP_DATA}/tmp/vela"
  (cd "${SNAP_DATA}/tmp/vela"
  fetch_as https://github.com/kubevela/kubevela/releases/download/${VELA_VERSION}/kubectl-vela-${VELA_VERSION}-linux-${SNAP_ARCH}.tar.gz "$SNAP_DATA/tmp/vela/vela.tar.gz"
  run_with_sudo gzip -q -d "$SNAP_DATA/tmp/vela/vela.tar.gz"
  run_with_sudo tar -xvf "$SNAP_DATA/tmp/vela/vela.tar"
  run_with_sudo chmod 777 "$SNAP_DATA/tmp/vela/linux-$SNAP_ARCH")
  run_with_sudo mkdir -p "$SNAP_DATA/bin/"
  run_with_sudo mv "$SNAP_DATA/tmp/vela/linux-$SNAP_ARCH/kubectl-vela" "$SNAP_DATA/bin/"
  run_with_sudo chmod +x "$SNAP_DATA/bin/"
  run_with_sudo cp $(dirname "$0")/microk8s-vela.wrapper $SNAP_COMMON/plugins/vela
  echo "Wrapper installed to $SNAP_COMMON/plugin/vela"
  run_with_sudo rm -rf "$SNAP_DATA/tmp/vela"
fi

"$SNAP/microk8s-enable.wrapper" dns

if [ ! -z "$#"  ]
then
  echo "Installing KubeVela"
  KUBECONFIG=$SNAP_DATA/credentials/client.config $SNAP_DATA/bin/kubectl-vela install -y ${ARGUMENTS[@]}
else
  echo "Installing KubeVela with default settings"
  KUBECONFIG=$SNAP_DATA/credentials/client.config $SNAP_DATA/bin/kubectl-vela install -y
fi

run_with_sudo touch "$SNAP_USER_COMMON/vela.lock"

echo "KubeVela is starting"
echo ""
