#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
KUBECTL="$SNAP/microk8s-kubectl.wrapper"
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
HELM="$SNAP/microk8s-helm3.wrapper"

echo "Disabling Dapr"


# Delete dapr configuration in default namespace

$KUBECTL delete -f "${CURRENT_DIR}/dapr.yaml" || true
$KUBECTL delete secret redis -n default
$KUBECTL delete deployment zipkin -n dapr-system -f 

$HELM uninstall dapr --namespace dapr-system

run_with_sudo rm -rf "${SNAP_DATA}/bin/dapr"
run_with_sudo rm -rf "$SNAP_USER_COMMON/dapr.lock"
run_with_sudo rm -rf "$SNAP_COMMON/plugins/dapr"


echo "Dapr is terminating"
