#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
HELM="$SNAP/microk8s-helm3.wrapper"

echo "Enabling Dapr"

if [ ! -f "${SNAP_DATA}/bin/dapr" ]
then
  DAPR_VERSION="v1.8.1"

  if ! [ $SNAP_ARCH == "arm64" ] && ! [ $SNAP_ARCH == "amd64" ]; then
    echo "Architecture $ARCH not supported"
    exit 1
  fi


  echo "Fetching Dapr CLI version $DAPR_VERSION for $SNAP_ARCH."
  run_with_sudo mkdir -p "${SNAP_DATA}/tmp/dapr"
  (cd "${SNAP_DATA}/tmp/dapr"
  fetch_as https://github.com/dapr/cli/releases/download/${DAPR_VERSION}/dapr_linux_${SNAP_ARCH}.tar.gz "$SNAP_DATA/tmp/dapr/dapr.tar.gz"
  run_with_sudo gzip -q -d "$SNAP_DATA/tmp/dapr/dapr.tar.gz"
  run_with_sudo tar -xvf "$SNAP_DATA/tmp/dapr/dapr.tar"
  run_with_sudo chmod 777 "$SNAP_DATA/tmp/dapr/dapr")
  run_with_sudo mkdir -p "$SNAP_DATA/bin/"
  run_with_sudo mv "$SNAP_DATA/tmp/dapr/dapr" "$SNAP_DATA/bin/"
  run_with_sudo chmod +x "$SNAP_DATA/bin/"
  run_with_sudo cp "${CURRENT_DIR}/microk8s-dapr.wrapper" "${SNAP_COMMON}/plugins/dapr"
  echo "Wrapper installed to $SNAP_COMMON/plugin/dapr"
  run_with_sudo rm -rf "${SNAP_DATA}/tmp/dapr"
fi

"${SNAP}/microk8s-enable.wrapper" dns storage redis
# Allow some time for the apiserver to start
"${SNAP}/microk8s-status.wrapper" --wait-ready --timeout 30 >/dev/null
$HELM repo add dapr https://dapr.github.io/helm-charts/
$HELM repo update
$HELM --namespace dapr-system --create-namespace --wait upgrade --install dapr dapr/dapr
$KUBECTL create deployment zipkin -n dapr-system --image openzipkin/zipkin
$KUBECTL expose deployment zipkin -n dapr-system --type ClusterIP --port 9411

"$SNAP/microk8s-status.wrapper" --wait-ready --timeout 30 >/dev/null

# add dapper components to default namespace

$KUBECTL apply -f "${CURRENT_DIR}/dapr.yaml"

# Copy redis secret to default namespace

$KUBECTL get secret redis --namespace=redis -o yaml | sed 's/namespace: .*/namespace: default/' | $KUBECTL apply -f -

run_with_sudo touch "$SNAP_USER_COMMON/dapr.lock"

echo "Dapr is starting"
echo ""
