#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

DEVTRON_NS="devtroncd"

echo "Disabling devtron"

$HELM uninstall devtron -n $DEVTRON_NS || true

