#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"
ISTIO_NS="istio-system"

echo "Enabling Istio"

if [ ! -f "${SNAP_DATA}/bin/istioctl" ]
then
  ISTIO_VERSION="1.15.1"

  if ! [ $SNAP_ARCH == "arm64" ] && ! [ $SNAP_ARCH == "amd64" ]; then
    echo "Architecture $ARCH not supported"
    exit 1
  fi
  echo "Fetching Istio CLI version $ISTIO_VERSION for $SNAP_ARCH."
  run_with_sudo mkdir -p "${SNAP_DATA}/tmp/istio"
  (cd "${SNAP_DATA}/tmp/istio"
  echo "Fetching https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istioctl-${ISTIO_VERSION}-linux-${SNAP_ARCH}.tar.gz "
  fetch_as https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istioctl-${ISTIO_VERSION}-linux-${SNAP_ARCH}.tar.gz "$SNAP_DATA/tmp/istio/istio.tar.gz"
  run_with_sudo gzip -q -d "$SNAP_DATA/tmp/istio/istio.tar.gz"
  run_with_sudo tar -xvf "$SNAP_DATA/tmp/istio/istio.tar"
  run_with_sudo mkdir -p "$SNAP_DATA/bin/"
  run_with_sudo mv "$SNAP_DATA/tmp/istio/istioctl" "$SNAP_DATA/bin/"
  run_with_sudo chmod +x "$SNAP_DATA/bin/"
  run_with_sudo cp $(dirname "$0")/microk8s-istioctl.wrapper $SNAP_COMMON/plugins/istioctl)
  echo "Wrapper installed to $SNAP_COMMON/plugin/istioctl"
  run_with_sudo rm -rf "$SNAP_DATA/tmp/istio"
fi

"$SNAP/microk8s-enable.wrapper" dns

if [ ! -z "$#"  ]
then
  echo "Installing Istio"
  $SNAP_DATA/bin/istioctl install --verify --set profile=demo --set meshConfig.enableTracing=true -y -c $SNAP_DATA/credentials/client.config ${ARGUMENTS[@]}
else
  echo "Installing Istio with default settings"
  $SNAP_DATA/bin/istioctl install --verify --set profile=demo --set meshConfig.enableTracing=true -y -c $SNAP_DATA/credentials/client.config
fi

# echo "Installing Kiali" 
# $HELM repo add kiali https://kiali.org/helm-charts
# $HELM repo update
# $HELM install --namespace $ISTIO_NS kiali-server kiali/kiali-server --set auth.strategy=anonymous --set external_services.istio.root_namespace=$ISTIO_NS --set login_token.signing_key="" --set server.web_root=/kiali --set external.services.grafana.enabled=true --set external.services.grafana.in_cluster_url="http://kube-prom-stack-grafana.observability:3000" --set external_services.prometheus.url="http://kube-prom-stack-kube-prome-prometheus.observability:9090"

run_with_sudo touch "$SNAP_USER_COMMON/istio.lock"

echo "Istio is available now."
echo ""
# echo "Open kiali dashboard with 'microk8s  istioctl dashboard kiali'"
