#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

echo "Enabling Istio"

if [ ! -f "${SNAP_DATA}/bin/istioctl" ]
then
  ISTIO_VERSION="v1.15.1"

  if ! [ $SNAP_ARCH == "arm64" ] && ! [ $SNAP_ARCH == "amd64" ]; then
    echo "Architecture $ARCH not supported"
    exit 1
  fi
  echo "Fetching Istio CLI version $ISTIO_VERSION for $SNAP_ARCH."
  run_with_sudo mkdir -p "${SNAP_DATA}/tmp/istio"
  (cd "${SNAP_DATA}/tmp/istio"
  fetch_as https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istio-${ISTIO_VERSION}-linux-${SNAP_ARCH}.tar.gz "$SNAP_DATA/tmp/istio/istio.tar.gz"
  run_with_sudo gzip -q -d "$SNAP_DATA/tmp/istio/istio.tar.gz"
  run_with_sudo tar -xvf "$SNAP_DATA/tmp/istio/istio.tar"
  run_with_sudo mkdir -p "$SNAP_DATA/bin/"
  run_with_sudo mv "$SNAP_DATA/tmp/istio-${ISTIO_VERSION}/bin/istioctl" "$SNAP_DATA/bin/"
  run_with_sudo chmod +x "$SNAP_DATA/bin/"
  run_with_sudo cp $(dirname "$0")/microk8s-istioctl.wrapper $SNAP_COMMON/plugins/istioctl)
  echo "Wrapper installed to $SNAP_COMMON/plugin/istioctl"
  run_with_sudo rm -rf "$SNAP_DATA/tmp/istio"
fi

"$SNAP/microk8s-enable.wrapper" dns

if [ ! -z "$#"  ]
then
  echo "Installing Istio"
  $SNAP_DATA/bin/istioctl install -c $SNAP_DATA/credentials/client.config ${ARGUMENTS[@]}
else
  echo "Installing Istio with default settings"
  $SNAP_DATA/bin/istioctl install -c $SNAP_DATA/credentials/client.config
fi

run_with_sudo touch "$SNAP_USER_COMMON/istio.lock"

echo "Istio is starting"
echo ""
