#!/usr/bin/env bash

set -eu

source "$SNAP/actions/common/utils.sh"

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

REDIS_NS="redis"

"$SNAP/microk8s-enable.wrapper" dns
"$SNAP/microk8s-enable.wrapper" helm3
"$SNAP/microk8s-enable.wrapper" hostpath-storage

# make sure the "redis" namespace exist
$KUBECTL create namespace "$REDIS_NS" > /dev/null 2>&1 || true

$HELM repo add bitnami https://charts.bitnami.com/bitnami
$HELM repo update
$HELM -n $REDIS_NS install redis bitnami/redis

echo "redis is installed"

